### ISSUE TITLE
Incorrect Robustess

### ISSUE THREAD

**Issue by ChaitraKeshavaMurthy** [decyphir/STLRom#2]
Thank you for your reply. Below the rule to be satisfied 
signal x
phi := alw_[0,11] (x[t] < 0.5)

This is my sample data
v = {0,0,0,0,0,0,1,1,1,0,0,0};

In this case I expect my robustness to be in negative since I have data violating the rule i.e 1 in the position 6,7,8.
But I get the robustness value as 0.5

_Originally posted by @ChaitraKeshavaMurthy in https://github.com/decyphir/STLRom/issues/1#issuecomment-1415962161_

**Comment by adonze** [comment]
Hello, 

Can you provide the time data ?  Or a code sample to reproduce your result, for better diagnosis.

**Comment by ChaitraKeshavaMurthy** [comment]
#include <stdio.h>
#include "stl_driver.h"
#include <string>
#include <vector>

using namespace std;
using namespace STLRom;

int main(int argc, char** argv) {

        /*  Read formula(s).

        Formulas can be defined in a file or a string. At minima there needs to be:
        - a signal(s) declaration
        - one formula assignement, e.g.:

        signal x,y
        phi := alw_[0, 5.] (x[t]>0 and y[t]<2)*/


    // STLDriver is the class implementing the parser.            
    
    STLDriver stl_driver = STLDriver();
    string s ="signal x,y\n";
    s+="phi:=";
    s+="alw_[0,11] (x[t] < 0.5)\n";
 
    bool parse_success = stl_driver.parse_string(s);

    if (parse_success) {
        cout << "Formula parsed successfully" << endl;    
        stl_driver.print();                    
        }
    else {
        cout << "Something went wrong." <<endl;
        return 1; 
    }  

    // Testing one sample
    vector<double> v ;
    v = {0,0,0,0,0,0,1,1,1,0,0,0};
    stl_driver.add_sample(v);

    vector<double> robs;
    robs = stl_driver.get_online_rob("phi");
    cout << robs[0] << " " << robs[1] << " " << robs[2] << endl;

    return 0;

}

**Comment by ChaitraKeshavaMurthy** [comment]
Thanks again for your reply
Unfortunately, it doesn't work when i have two rules to evaluate .
Below is my rule and corresponding data samples. The robustness returned for this code is 0.5

STLDriver stl_driver = STLDriver();
    string s ="signal x,y\n";
    s+="phi:=";
    s+="alw_[0,11] (x[t] < 0.5 and y[t] < 0.5)\n";
 
    bool parse_success = stl_driver.parse_string(s);

    if (parse_success) {
        cout << "Formula parsed successfully" << endl;    
        stl_driver.print();                    
        }
    else {
        cout << "Something went wrong." <<endl;
        return 1; 
    }  

    vector<double> t;
    t = {0,1,2,3,4,5,6,7,8,9,10,11};  

    std::vector<double> x_trace;
    x_trace = {0,0,0,0,0,0,0,0,0,0,0,0}; 
    for (int i=0; i<=500; i++) {
        vector<double> sample = {t[i],
                                 x_trace[i]};
        stl_driver.add_sample(sample);
    }

    std::vector<double> y_trace;
    y_trace = {0,0,0,0,1,0,0,0,0,0,0,0}; 
    for (int i=0; i<=500; i++) {
        vector<double> sample = {t[i],
                                 y_trace[i]};
        stl_driver.add_sample(sample);
    }

**Comment by adonze** [comment]
Almost there :) 
A sample in your case is a vector (time, x, y) so you need to add x and y together: 

```c++
vector<double> t;
t = {0,1,2,3,4,5,6,7,8,9,10,11};  

std::vector<double> x_trace;
x_trace = {0,0,0,0,0,0,0,0,0,0,0,0}; 
std::vector<double> y_trace;
y_trace = {0,0,0,0,1,0,0,0,0,0,0,0}; 

for (int i=0; i<=500; i++) {
    vector<double> sample = {t[i], x_trace[i], y_trace[i] };
    stl_driver.add_sample(sample);
}
```
